services:
  - type: web
    name: n8n-on-render
    env: node
    plan: free
    branch: main
    repo: https://github.com/your-username/your-n8n-repo
    buildCommand: ""
    startCommand: n8n start --tunnel
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: supersecret
